project_id = "found-poems"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = []
max_rows = 200

[db]
major_version = 15
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323
